# NumPy Array Basics Exercise

This exercise practices creating and working with NumPy arrays, including:
- One-dimensional arrays
- Two-dimensional arrays
- Three-dimensional arrays
- Checking data types
- Array transposing
- Array slicing

In [1]:
import numpy as np

## Array Basics

In [2]:
# Create a standard Python list
fruits = ["apple", "banana", "cherry", "date"]

print(fruits)

['apple', 'banana', 'cherry', 'date']


In [3]:
#Create a one-dimensional NumPy array
arr_1 = np.array(fruits)

print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
# Check the data type of values in arr_1
print(arr_1.dtype)

# The returned dtype will likely be something like <U6
# U means Unicode string
# 6 means the maximum string length in the array is 6 characters


<U6


In [6]:
# Create a two-dimensional array
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
# Print the transposed version of arr_2
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [8]:
# Check whether arr_2 was permanently changed
print(arr_2)

# No, using .T does not permanently alter arr_2.
# It only displays a transposed view of the array.

[[10 11 12]
 [13 14 15]]


In [9]:
# Create another two-dimensional array
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [10]:
# Create arr_4 using slicing/indexing
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

[5 4]


In [11]:
# Create a three-dimensional array of all 1's
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
