# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

## Looping Through Arrays

In [3]:
# Create arrA
arrA = np.array([[11, 12, 13],
                 [14, 15, 16]])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [4]:
# Loop through the first dimension
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
# Loop through the second dimension
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop goes through each row of the array, so multiplying by 2 affects an entire row at once.  
The second loop goes through each individual value inside the rows, so it prints each number separately multiplied by 2.

In [6]:
# Loop through the second dimension again
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents the entire row,
# not the individual value y. So the whole row is multiplied by 2 each time.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [7]:
# Concatenate on axis=0
joined_array_1 = np.concatenate((arrA, arrA))

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [8]:
# Concatenate on axis=1
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [9]:
# Stack joined_array_1 with itself
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [10]:
# Attempt to stack arrays of different shapes
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

print(stacked_array_2)

# Error explanation:
# np.stack() requires arrays to have the exact same shape.
# joined_array_1 and joined_array_2 have different dimensions,
# so NumPy returns a shape mismatch error.

ValueError: all input arrays must have the same shape

In [11]:
# Concatenate joined_array_1 with arrA
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [14]:
# Attempt concatenation on axis=1
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

print(another_2)

# Error explanation:
# The arrays do not have the same number of rows,
# so NumPy cannot join them side-by-side on axis=1.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [13]:
# hstack joins arrays horizontally (side-by-side)
horizontal_stack = np.hstack((arrA, arrA))
print(horizontal_stack)

# vstack joins arrays vertically (top-to-bottom)
vertical_stack = np.vstack((arrA, arrA))
print(vertical_stack)

# dstack joins arrays depth-wise (creates a third dimension)
depth_stack = np.dstack((arrA, arrA))
print(depth_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [15]:
# Split joined_array_1 into 2 sections
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# Result explanation:
# This creates 2 arrays.
# Each array is still 2-dimensional.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [16]:
# Split joined_array_1 into 3 sections
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

# Result explanation:
# This creates 3 arrays.
# Each resulting array is still 2-dimensional,
# but the rows are divided as evenly as possible.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [17]:
# Replace odd numbers with 'odd'
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')

print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [18]:
# Create arrB
arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])

# Sort arrB
arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [19]:
# Filter values less than 7
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [20]:
# Filter values greater than or equal to 7
y = arrB >= 7

arrD = arrB[y]

print(arrD)

[ 7 13  7]
