# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [3]:
# Random integers between 1 and 20 with 2 elements
r_1 = np.random.randint(1, 21, size=2)

print(r_1)

[17  1]


In [4]:
# Random integers between 1 and 20 with 1 row and 2 columns
r_2 = np.random.randint(1, 21, size=(1, 2))

print(r_2)

[[9 5]]


In [5]:
# Random floats between 0 and 1 with 2 rows and 1 column
r_3 = np.random.rand(2, 1)

print(r_3)

[[0.3634714 ]
 [0.75953484]]


In [6]:
# Random integers between 20 and 100 with 4 rows and 5 columns
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[41 95 53 34 65]
 [55 53 85 92 29]
 [24 26 93 54 77]
 [70 89 91 85 25]]


In [7]:
# Random floats between 0 and 1 with 4 rows and 5 columns
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.85351864 0.076949   0.76964023 0.22092146 0.47666386]
 [0.7353962  0.38410289 0.12214772 0.14569923 0.37374679]
 [0.75047044 0.91790361 0.35812264 0.96875601 0.11561864]
 [0.4965439  0.19430244 0.34058419 0.90895236 0.53008355]]


## Generating Random Choices from an Array

In [8]:
# Array of student names
students = np.array([
    "Alex", "Brianna", "Carlos", "Danielle",
    "Ethan", "Fatima", "Grace", "Hector",
    "Isabella", "Jordan", "Kayla", "Liam"
])

print(students)

['Alex' 'Brianna' 'Carlos' 'Danielle' 'Ethan' 'Fatima' 'Grace' 'Hector'
 'Isabella' 'Jordan' 'Kayla' 'Liam']


In [10]:
# Choose one random student
call_on = np.random.choice(students)

print(call_on)

Brianna


In [11]:
# Random breakout groups
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This may not be the best way to assign breakout groups
# because the same student can appear multiple times
# while some students may not appear at all.

[['Fatima' 'Danielle' 'Fatima' 'Danielle']
 ['Danielle' 'Ethan' 'Isabella' 'Brianna']
 ['Ethan' 'Danielle' 'Hector' 'Jordan']]


In [12]:
# Weighted random selections
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[
        0.30,  # Alex
        0.10,  # Brianna
        0.05,  # Carlos
        0.00,  # Danielle
        0.10,  # Ethan
        0.05,  # Fatima
        0.05,  # Grace
        0.10,  # Hector
        0.05,  # Isabella
        0.05,  # Jordan
        0.10,  # Kayla
        0.05   # Liam
    ]
)

print(call_on_weighted)

# Probability explanation:
# Alex has a 30% chance of being selected.
# Danielle has a 0% chance of being selected.
# The remaining students have smaller probabilities
# distributed across the rest of the class.

['Alex' 'Grace' 'Alex' 'Ethan' 'Alex']


## Generating a Normal Distribution

In [13]:
# Generate a normal distribution
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[10.72671967  4.03048147  6.59021695  2.62316396  2.28187424]
 [ 4.49648231  3.02921085 10.1207632  10.67185694 16.9679416 ]
 [ 6.80003971  5.58565615 14.13511185  4.15249293  7.07813171]
 [11.25654352  7.19211021  7.23355598 15.43147977 11.53159479]]
