# Exercise 1.C Performing Operations on Arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
# Random sample arrays copied from Exercise 1.B

r_1 = np.random.randint(1, 21, size=2)

r_2 = np.random.randint(1, 21, size=(1, 2))

r_3 = np.random.rand(2, 1)

r_4 = np.random.randint(20, 101, size=(4, 5))

r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

[1 8]
[[13  3]]
[[0.78065417]
 [0.96896923]]
[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]
[[0.77191209 0.40767599 0.00551551 0.13330613 0.90702352]
 [0.40375447 0.5615951  0.88665256 0.56700532 0.03137354]
 [0.65044361 0.9362207  0.7129956  0.15233608 0.75644533]
 [0.20372547 0.57461396 0.13978359 0.67429004 0.13157421]]


## Permutations

In [3]:
# Print current r_4
print(r_4)

[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]


In [4]:
# Shuffle r_4
np.random.shuffle(r_4)

print(r_4)

[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]


The shuffle function rearranges the rows of the array.  
The values inside each row stay together, but the order of the rows changes.

In [5]:
# Create a permutation of r_4
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)

# Print original r_4 again
print(r_4)

[[26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]
 [45 31 68 32 87]]
[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]


shuffle changes the original array directly.  
permutation creates a shuffled copy and leaves the original array unchanged.

## Mathematical Operations

In [6]:
# Add r_1 and r_2

print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result_1 = np.add(r_1, r_2)

print(result_1)
print(result_1.shape)

[1 8]
(2,)
[[13  3]]
(1, 2)
[[14 11]]
(1, 2)


In [7]:
# Add r_1 and r_3

print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result_2 = np.add(r_1, r_3)

print(result_2)
print(result_2.shape)

[1 8]
(2,)
[[0.78065417]
 [0.96896923]]
(2, 1)
[[1.78065417 8.78065417]
 [1.96896923 8.96896923]]
(2, 2)


In [11]:
# Add r_2 and r_4
r_2 = np.random.randint(1, 21, size=(1,5))

print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result_3 = np.add(r_2, r_4)

print(result_3)
print(result_3.shape)

[[16  1  9  7  1]]
(1, 5)
[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]
(4, 5)
[[61 32 77 39 88]
 [42 59 99 61 37]
 [46 58 38 56 44]
 [61 85 51 96 91]]
(4, 5)


In [12]:
# Attempt to add r_1 and r_4

result_4 = np.add(r_1, r_4)

print(result_4)

# Error explanation:
# r_1 has only 2 values while r_4 has 5 columns.
# Their shapes are incompatible for broadcasting.

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [13]:
# Add np.array([1]) to r_4

print(np.add(r_4, np.array([1])))

[[46 32 69 33 88]
 [27 59 91 55 37]
 [31 58 30 50 44]
 [46 85 43 90 91]]


In [14]:
# Add np.array([[1]]) to r_4

print(np.add(r_4, np.array([[1]])))

[[46 32 69 33 88]
 [27 59 91 55 37]
 [31 58 30 50 44]
 [46 85 43 90 91]]


In [15]:
# Add np.array([1,1,1,1,1]) to r_4

print(np.add(r_4, np.array([1,1,1,1,1])))

[[46 32 69 33 88]
 [27 59 91 55 37]
 [31 58 30 50 44]
 [46 85 43 90 91]]


In [16]:
# Attempt to add [[1],[1]] to r_4

print(np.add(r_4, np.array([[1],[1]])))

# Error explanation:
# The array has shape (2,1) which does not match
# the shape of r_4, so broadcasting fails.

ValueError: operands could not be broadcast together with shapes (4,5) (2,1) 

Broadcasting allows NumPy to perform math operations on arrays with different shapes
when the dimensions are compatible.

When using add(), NumPy lines up the arrays from right to left and stretches smaller
arrays to match larger arrays when possible.

The resulting array usually takes the shape of the larger array after broadcasting.

## Rounding

In [18]:
# Print r_3
print(r_3)

[[0.78065417]
 [0.96896923]]


In [19]:
# trunc
print(np.trunc(r_3))

[[0.]
 [0.]]


In [20]:
# fix
print(np.fix(r_3))

[[0.]
 [0.]]


In [21]:
# floor
print(np.floor(r_3))

[[0.]
 [0.]]


In [22]:
# ceil
print(np.ceil(r_3))

[[1.]
 [1.]]


In [23]:
# round to 2 decimal places
print(np.round(r_3, 2))

[[0.78]
 [0.97]]


## Cumulative Operations

In [24]:
# Print r_4
print(r_4)

[[45 31 68 32 87]
 [26 58 90 54 36]
 [30 57 29 49 43]
 [45 84 42 89 90]]


In [25]:
# Sum of all values
print(np.sum(r_4))

1085


In [26]:
# Sum along axis 0
print(np.sum(r_4, axis=0))

[146 230 229 224 256]


In [27]:
# Sum along axis 1
print(np.sum(r_4, axis=1))

[263 264 208 350]


In [28]:
# Cumulative sum of all values
print(np.cumsum(r_4))

[  45   76  144  176  263  289  347  437  491  527  557  614  643  692
  735  780  864  906  995 1085]


In [29]:
# Cumulative sum along axis 0
print(np.cumsum(r_4, axis=0))

[[ 45  31  68  32  87]
 [ 71  89 158  86 123]
 [101 146 187 135 166]
 [146 230 229 224 256]]


## Grocery Problem

In [30]:
# Grocery bags
# Order: vegetables, fruits, snacks, beverages

bag1 = np.array([2, 3, 4, 0])

bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [31]:
# Total items in each bag

bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [32]:
# Total items in each category

totals = np.add(bag1, bag2)

print(f"There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [33]:
# Ali's door knocks
ali = np.array([5, 4, 6, 4, 2])

print(ali)

[5 4 6 4 2]


In [34]:
# Ben's door knocks
# Monday = 0 because he missed that day

ben = np.array([0, 5, 5, 3, 4])

print(ben)

[0 5 5 3 4]


In [35]:
# Carla's door knocks
# Wednesday = 0 because she was sick

carla = np.array([3, 6, 0, 3, 4])

print(carla)

[3 6 0 3 4]


In [36]:
# Combine all values into one array

all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [37]:
# Total doors knocked by each person

ali_total = np.sum(ali)
ben_total = np.sum(ben)
carla_total = np.sum(carla)

group_total = np.sum(all_knocks)

print(f"Ali knocked on {ali_total} doors.")
print(f"Ben knocked on {ben_total} doors.")
print(f"Carla knocked on {carla_total} doors.")
print(f"The group knocked on {group_total} doors total.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.
The group knocked on 54 doors total.


In [38]:
# Rolling total of estimated votes

daily_totals = np.sum(all_knocks, axis=0)

rolling_total = np.cumsum(daily_totals)

estimated_votes = rolling_total * 0.5

print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
